// This file was generated by Prisma, and assumes you have installed the following:
// Load .env in dev (dotenv is a devDependency, not available in production image)
try { await import("dotenv/config"); } catch {}
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
